# This is a basic workflow to help you get started with Actions

name: Build Document

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document - Pass 1
        uses: xu-cheng/latex-action@v2
        with:
          root_file: fca-report.tex
          compiler: xelatex
          args: -file-line-error -interaction=nonstopmode
      - name: Compile BibTex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: fca-report
          compiler: bibtex
      - name: Compile LaTeX document - Pass 2
        uses: xu-cheng/latex-action@v2
        with:
          root_file: fca-report.tex
          compiler: xelatex
          args: -file-line-error -interaction=nonstopmode
      - name: Upload PDF to artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: PDF
          path: fca-report.pdf
