# This is a basic workflow to help you get started with Actions

name: Build Document

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Pre-compile LaTeX document for BibTex
        uses: xu-cheng/texlive-action/full@v1
        with:
          run:
            xelatex -file-line-error -interaction=nonstopmode fca-report.tex
      - name: Compile BibTex
        uses: xu-cheng/texlive-action/full@v1
        with:
          run:
            bibtex fca-report
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            xelatex -file-line-error -interaction=nonstopmode fca-report.tex
            xelatex -file-line-error -interaction=nonstopmode fca-report.tex
      - name: Upload PDF to artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: fca-report PDF File
          path: fca-report.pdf
